// Comidas comunes (porción típica) para autocompletar kcal y macros.
// Valores aproximados: el objetivo es estimar, no ser exactos.
export const BASE_COMIDAS = [
  { nombre: "Milanesa con puré", kcal: 650, carbG: 55, protG: 35, fatG: 30 },
  { nombre: "Milanesa", kcal: 400, carbG: 20, protG: 30, fatG: 22 },
  { nombre: "Empanada de carne", kcal: 300, carbG: 25, protG: 12, fatG: 16 },
  { nombre: "Empanada de jamón y queso", kcal: 290, carbG: 26, protG: 11, fatG: 15 },
  { nombre: "Porción de pizza", kcal: 275, carbG: 30, protG: 12, fatG: 12 },
  { nombre: "Pizza (2 porciones)", kcal: 550, carbG: 60, protG: 24, fatG: 24 },
  { nombre: "Asado (porción)", kcal: 550, carbG: 0, protG: 45, fatG: 40 },
  { nombre: "Choripán", kcal: 500, carbG: 35, protG: 20, fatG: 30 },
  { nombre: "Fideos con tuco", kcal: 550, carbG: 90, protG: 15, fatG: 12 },
  { nombre: "Ñoquis con salsa", kcal: 500, carbG: 95, protG: 12, fatG: 8 },
  { nombre: "Ravioles con salsa", kcal: 520, carbG: 85, protG: 16, fatG: 10 },
  { nombre: "Arroz con pollo", kcal: 550, carbG: 70, protG: 35, fatG: 12 },
  { nombre: "Pollo al horno con papas", kcal: 600, carbG: 45, protG: 40, fatG: 28 },
  { nombre: "Bife con ensalada", kcal: 450, carbG: 10, protG: 40, fatG: 28 },
  { nombre: "Pescado con arroz", kcal: 480, carbG: 55, protG: 35, fatG: 10 },
  { nombre: "Hamburguesa completa", kcal: 650, carbG: 45, protG: 30, fatG: 38 },
  { nombre: "Lomito completo", kcal: 700, carbG: 50, protG: 40, fatG: 35 },
  { nombre: "Pancho", kcal: 350, carbG: 30, protG: 12, fatG: 20 },
  { nombre: "Tarta de verdura (porción)", kcal: 300, carbG: 25, protG: 12, fatG: 17 },
  { nombre: "Tortilla de papas (porción)", kcal: 350, carbG: 30, protG: 10, fatG: 20 },
  { nombre: "Guiso de lentejas", kcal: 450, carbG: 60, protG: 22, fatG: 12 },
  { nombre: "Polenta con queso", kcal: 450, carbG: 60, protG: 15, fatG: 16 },
  { nombre: "Sopa de verduras", kcal: 120, carbG: 20, protG: 4, fatG: 2 },
  { nombre: "Ensalada mixta", kcal: 150, carbG: 10, protG: 3, fatG: 10 },
  { nombre: "Ensalada césar", kcal: 350, carbG: 15, protG: 20, fatG: 24 },
  { nombre: "Sushi (10 piezas)", kcal: 450, carbG: 70, protG: 18, fatG: 8 },
  { nombre: "Papas fritas (porción)", kcal: 400, carbG: 50, protG: 5, fatG: 20 },
  { nombre: "Sándwich de miga (2)", kcal: 300, carbG: 30, protG: 14, fatG: 13 },
  { nombre: "Tostado de jamón y queso", kcal: 400, carbG: 35, protG: 20, fatG: 18 },
  { nombre: "Huevos revueltos (2)", kcal: 180, carbG: 2, protG: 13, fatG: 13 },
  { nombre: "Avena con leche", kcal: 300, carbG: 45, protG: 12, fatG: 8 },
  { nombre: "Yogur con granola", kcal: 280, carbG: 40, protG: 10, fatG: 8 },
  { nombre: "Tostadas con mermelada (2)", kcal: 220, carbG: 42, protG: 4, fatG: 3 },
  { nombre: "Café con leche", kcal: 90, carbG: 9, protG: 5, fatG: 4 },
  { nombre: "Medialuna", kcal: 190, carbG: 22, protG: 4, fatG: 9 },
  { nombre: "Facturas (2)", kcal: 380, carbG: 44, protG: 8, fatG: 18 },
  { nombre: "Mate con bizcochitos", kcal: 250, carbG: 30, protG: 4, fatG: 12 },
  { nombre: "Alfajor", kcal: 200, carbG: 28, protG: 3, fatG: 8 },
  { nombre: "Helado (2 bochas)", kcal: 250, carbG: 30, protG: 4, fatG: 12 },
  { nombre: "Banana", unidad: "unidad", gramos: 120, kcal: 90, carbG: 23, protG: 1, fatG: 0 },
  { nombre: "Manzana", unidad: "unidad", gramos: 150, kcal: 80, carbG: 21, protG: 0, fatG: 0 },

  // ---- Merienda / porciones chicas (traen su unidad natural y gramos aprox.) ----
  { nombre: "Yogur bebible", unidad: "pote", gramos: 185, kcal: 130, carbG: 22, protG: 6, fatG: 2 },
  { nombre: "Yogur con cereales", unidad: "pote", gramos: 190, kcal: 170, carbG: 28, protG: 8, fatG: 3 },
  { nombre: "Yogur natural", unidad: "pote", gramos: 170, kcal: 100, carbG: 12, protG: 6, fatG: 3 },
  { nombre: "Granola", unidad: "puñado", gramos: 30, kcal: 140, carbG: 20, protG: 4, fatG: 5 },
  { nombre: "Avena", unidad: "cucharada", gramos: 10, kcal: 40, carbG: 7, protG: 1, fatG: 1 },
  { nombre: "Mermelada", unidad: "cucharada", gramos: 20, kcal: 50, carbG: 13, protG: 0, fatG: 0 },
  { nombre: "Dulce de leche", unidad: "cucharada", gramos: 20, kcal: 65, carbG: 11, protG: 1, fatG: 2 },
  { nombre: "Queso untable", unidad: "cucharada", gramos: 20, kcal: 55, carbG: 1, protG: 2, fatG: 5 },
  { nombre: "Manteca de maní", unidad: "cucharada", gramos: 16, kcal: 95, carbG: 3, protG: 4, fatG: 8 },
  { nombre: "Miel", unidad: "cucharada", gramos: 21, kcal: 60, carbG: 17, protG: 0, fatG: 0 },
  { nombre: "Pan", unidad: "rebanada", gramos: 25, kcal: 75, carbG: 14, protG: 2, fatG: 1 },
  { nombre: "Tostada", unidad: "unidad", gramos: 15, kcal: 60, carbG: 11, protG: 2, fatG: 1 },
  { nombre: "Galletita de agua", unidad: "unidad", gramos: 7, kcal: 30, carbG: 5, protG: 1, fatG: 1 },
  { nombre: "Galletita dulce", unidad: "unidad", gramos: 10, kcal: 45, carbG: 7, protG: 1, fatG: 2 },
  { nombre: "Vaso de leche", unidad: "vaso", gramos: 200, kcal: 120, carbG: 12, protG: 8, fatG: 5 },
  { nombre: "Té", unidad: "taza", gramos: 200, kcal: 5, carbG: 1, protG: 0, fatG: 0 },
  { nombre: "Mate cocido", unidad: "taza", gramos: 200, kcal: 10, carbG: 2, protG: 0, fatG: 0 },
  { nombre: "Fruta", unidad: "unidad", gramos: 120, kcal: 80, carbG: 20, protG: 1, fatG: 0 },
  { nombre: "Frutos secos", unidad: "puñado", gramos: 30, kcal: 170, carbG: 6, protG: 5, fatG: 15 },
  { nombre: "Barrita de cereal", unidad: "unidad", gramos: 25, kcal: 110, carbG: 20, protG: 2, fatG: 3 },
];
